### ISSUE TITLE
Use case for sharing memory-cached dataset across processes.

### ISSUE THREAD

**Issue by hukz18** [FI-Mihej/InterProcessPyObjects#4]
Hi Mihej, 

Thank you for your contributions to creating this repo, I'm trying to make use of it in the following scenario, which I think may help others as well so I'm creating an issue here:

I'm writing a PyTorch program that involves training on a large dataset, and I want to cache the whole dataset to memory to speed up training. However, since the dataset is large and I want to run multiple hyperparameter settings at the same time and the same dataset, I want to share the cached dataset across different runs. Could you give a simple example of how I can achieve this?

I think a `SharedMemory` class and the `put_message(dataset)`, `take_message(dataset)` methods should work, but I'm not sure if I can call the `take_message` multiple times across different runs once I've put it.

The dataset I want to cache has the following form:
```
cached_dataset = [
data_1, # dictionary of several numpy arrays like images, etc
data_2,
...,
]
```
Do you have any advice on how I can improve the reading performance of the shared dataset? And after I've put the cached dataset into the shared memory, is it safe for me to delete the original cached dataset so that it won't take up twice of the memory?

Thank you for the help!

**Comment by FI-Mihej** [comment]
Hi @hukz18, thank you for your interest!

First of all, feel free to use `read_message` instead of `take_message`. It will read an object from the message but will not delete the message from the queue. That means you can safely take the same shared object multiple times.

The overall architecture can vary depending on your situation. Here are two possibilities:
# 1. Single Process at Each Moment in Time

If you are trying to run your training script multiple times in a row in a sequenced manner (such that there is either no instance or no more than one instance of your training process in memory at a time) and just want to preload data for those runs, follow these steps:

1. Spawn a Creator process that will `put_message` with your shared data and then persist permanently.
2. In the main loop of your working process:
    a. Spawn a Consumer that will `read_message` and work on your preloaded data.
    b. Finish your Consumer instance.
    c. Spawn another instance of your Consumer that will `read_message` and work on your preloaded data.
    d. Finish another instance of your Consumer.
    e. ... (Repeat as necessary)

# 2. Multiple Processes at Each Moment in Time

If you need to share data between multiple instances (processes) of your training scripts at the same time (in parallel):

In this situation, you'll need to wait for my next release (probably by next Monday). I've added support for symmetric multiprocessing (SMP).

If you have any additional questions, please feel free to use either [Discussions](https://github.com/FI-Mihej/InterProcessPyObjects/discussions) or [Cengal Discord](https://discord.gg/TAy7xNgR).

**Comment by hukz18** [comment]
Thanks for your reply! I'm waiting for the SMP features, I'm glad to try it out :-)
